networks:
  mynetwork:
    external: false

services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    container_name: blockchain-node
    volumes:
      - ./blockchain:/app
      - ./artifacts:/app/artifacts
    ports:
      - "8545:8545"
      - "3000:3000" # Port du serveur Express
    networks:
      - mynetwork

  site:
    image: django-docker:0.0.1
    build:
      context: backend/
      dockerfile: Dockerfile
    # container_name: site
    env_file: .env
    volumes:
      - site_media:/app/app/media
      - site_static:/app/static
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    container_name: db
    env_file: .env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 7526
      POSTGRES_DB: "db"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

volumes:
  db_data:
  site_static:
  site_media:
