services:
  
  #db:
  #  image: "postgres:latest"
  # ports:
  
  django:
    container_name: django
    build:
      context: ./backend/django/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#    depends_on:

    env_file: .env
#    volumes:

#  nginx:
#        container_name: nginx
#        image: nginx:alpine
#        networks:
#            - transcendence
#        ports:
#            - "443:443"
#        volumes:
#            - ./srcs/backend/nginx/
#        restart: on-failure

#networks:
#  transcendence:
#    name: transcendence
#    driver: bridge