# Generated by Django 5.1.5 on 2025-01-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_elo_rating_user_is_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
