# Generated by Django 5.1.5 on 2025-01-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_channel_is_private_game_player1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_y',
            field=models.FloatField(default=0.5),
        ),
    ]
