# Generated by Django 5.1.5 on 2025-02-04 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_player1_score_game_score_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball_super_speed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='max_score',
            field=models.IntegerField(blank=True, default=11, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='game',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
