# Generated by Django 5.1.5 on 2025-02-05 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_game_ball_super_speed_game_max_score_game_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='ball_x',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='game',
            name='ball_y',
            field=models.FloatField(default=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_y',
            field=models.FloatField(default=170),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_y',
            field=models.FloatField(default=170),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default/avatar.png', upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
